
FROM python:latest

WORKDIR /nguy1132/logging_service

COPY . /nguy1132/logging_service

RUN pip3 install flask requests

ENV FLASK_APP=app.py

EXPOSE 9003

CMD ["flask", "run", "--host=0.0.0.0", "--port=5003"]