FROM python:latest

WORKDIR /nguy1132/document_searching

COPY . /nguy1132/document_searching

RUN pip3 install flask requests

ENV FLASK_APP=app.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=5002"]